version: '3'

volumes:
  mongodb_volume:

services:
  bak-blog:
    build: ./
    ports:
      - 3453:3453
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongodb_volume:/data/db
    restart: always
